name: Process LeetCode Solution

on:
  push:
    branches:
      - main
    paths:
      - '**.py'  # Python files
      - '**.java' # Java files
      - '**.go'   # Go files
  workflow_dispatch:  # Allow manual trigger

jobs:
  process-solution:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to identify new/changed files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai pyyaml python-frontmatter
          
      - name: Identify new/modified solution files
        id: changed-files
        run: |
          # Get list of modified solution files (Python, Java, Go)
          NEW_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.(py|java|go)$' || echo "")
          echo "Changed solution files: $NEW_FILES"
          echo "new_files=$NEW_FILES" >> $GITHUB_OUTPUT
          
      - name: Process LeetCode solutions
        if: steps.changed-files.outputs.new_files != ''
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python _scripts/generate_solution_post.py
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          
      - name: Install Jekyll
        run: |
          gem install jekyll bundler
          bundle install
          
      - name: Build site
        run: |
          bundle exec jekyll build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
